app/main/routes.py
from flask import render_template, request, Blueprint
from app.models import Post

main = Blueprint('main', __name__)


@main.route('/', methods=['GET','POST'])
def index():
    # posts = Post.query.all()
    page = request.args.get('page', type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=3)
    return render_template ('index.html',judul='Home', posts=posts)

@main.route('/about')
def about():
    return render_template('about.jinja', judul='About')

app/posts/routes.py
import imp
from flask import (render_template, redirect, 
                  request, url_for, flash, 
                  abort, Blueprint)
from flask_login import login_required, current_user
from app import db
from app.models import Post
from app.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['get','post'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        posts = Post(title=form.title.data, content=form.content.data, author=current_user )
        db.session.add(posts)
        db.session.commit()        
        flash('Postingan berhasil diupload','success')
        return redirect(url_for('main.index'))
    return render_template('create_post.html', form=form, judul='New Post', legend='Create Postingan')


@posts.route('/post/<int:post_id>')
def postingan(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('postingan.html', judul=post.title, post=post)


@posts.route('/post/<int:post_id>/update', methods=['GET','POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data 
        post.content = form.content.data    
        db.session.commit()
        flash('Postingan anda berhasil diupdate','success')
        return redirect(url_for('main.index'))
    else:
        form.title.data = post.title
        form.content.data = post.content    
    return render_template('create_post.html', form=form, judul=post.title, post=post, legend='Update Postingan')


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Postingan berhasil dihapus','success')
    return redirect(url_for('main.index'))

app/users/routes.py
import imp
from flask import (render_template, redirect, 
                   request, url_for, flash, Blueprint)
from flask_login import login_user, current_user, logout_user, login_required
from app import db, bcrypt            
from app.models import User, Post
from app.users.forms import (RegisterForm, LoginForm, AccountForm, 
                             RequestResetForm, ResetPasswordForm)
from app.users.utils import save_picture, send_reset_email                             

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegisterForm()
    if form.validate_on_submit():
        hash_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hash_pw)
        db.session.add(user)
        db.session.commit()
        flash('Akun berhasil dibuat, silakan', 'success')
        return redirect(url_for('users.register'))
    return render_template ('register.html', form=form ,judul='Register')


@users.route('/login', methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
        else:
            flash('gagal login, silakan coba lagi.','danger')
    return render_template ('login.html', form=form, judul='Login')


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))


@users.route('/account', methods=['get','post'])
@login_required
def account():
    form = AccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data     
        db.session.commit()
        flash('profil berhasil diupdate','success')
        return redirect(url_for('users.account'))
    else:
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='img/' + current_user.image_file)
    return render_template('account.html', image_file=image_file, form=form, judul='Account')


@users.route("/user/<string:username>")
def user_post(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_post.html', judul=user.username, posts=posts, user=user)
     

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash(f'Kami telah mengirim email pengaturan ulang kata sandi Anda! Silakan cek email {form.email.data}.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Tautan ini telah kedaluwarsa, silakan mengulang', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Password anda berhasil di update, silakan login', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

app/templates/about.jinja
{% extends 'layout.html' %}


{% block content %}
    <h1 class="text-center" style="padding: 250px;">Hello, Welcome to About page</h1>
{% endblock content %}
    

app/templates/about.jinja2
{% extends 'layout.jinja2' %}


{% block content %}
    <h1 class="text-center" style="padding: 250px;">Hello, Welcome to About page</h1>
{% endblock content %}
    

app/templates/account.html
{% extends 'layout.html' %}


{% block content %}
<div class="container text-center">
    <div class="mr-5">
        <h4 style="padding-top:100px;padding-left:40px;">Account Info</h4>
    </div>
    <div>
        <img class="rounded-circle mt-2" style="height: 200px;width: 210px;" src="{{ image_file }}">
    </div>
    <div class="mt-3">
        <h3>{{ current_user.username}}</h3>
        <p>{{ current_user.email }}</p>        
    </div> <hr>

    <div class="container text-center">
        <div class="mr-5">
            <h5 style="padding-left:40px;">Update Account</h5>
        </div>
        <div class="mt-5">
            <form action="" method="POST" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <div class="text-center" style="width: 300px; margin-left: 36%;">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                    {% endwith %}
                </div>
                <div class="input-group mb-3" style="width: 300px; margin-left: 36%;">
                    <div class="input-group-append ">
                        <span class="btn btn-primary"><i class="fa fa-user"></i></span>
                    </div>
                    {% if form.username.errors %}
                        {{ form.username(class='form-control is-invalid input_user', placeholder='username') }}
                        <div class="text-center invalid-feedback">
                            {% for error in form.username.errors %}
                            {{error}}
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class='form-control input_user', placeholder='username') }}
                    {% endif %}
                </div>
                <div class="input-group mb-2" style="width: 300px;margin-left: 36%;padding-bottom:10px">
                    <div class="input-group-append">
                        <span class="btn btn-primary"><i class="fa fa-envelope"></i></span>
                    </div>
                    {% if form.email.errors %}o
                        {{ form.email(class='form-control is-invalid input_user', placeholder='email') }}
                        <div class="text-center invalid-feedback">
                            {% for error in form.email.errors %}
                            {{error}}
                            {% endfor %}
                        </div>
                    {% else %}
                       {{ form.email(class='form-control input_user', placeholder='email') }}
                    {% endif %}
                </div> 
                <div class="input-group mb-2" style="width: 300px;margin-left: 36%">                
                    {{ form.picture.label(class='ml-5 pl-5') }}
                    {{ form.picture(class='form-control-file ml-5 pl-1')}}
                    {% if form.picture.errors %}
                            {% for error in form.picture.errors %}
                                <small class="text-danger">
                                    {{error}}
                                </small>
                            {% endfor %}
                    {% endif %}
                </div> <br>
                <div class="d-flex justify-content-center mt-3 login_container">
                    {{ form.submit(class='btn btn-primary') }}
                </div>    
        </div>  
    </div>      
</div>

{% endblock content %}

app/templates/create_post.html
{% extends 'layout.html' %}


{% block content %}
<div class="container" style="padding:0 50 50 50;">
        <legend style="margin-bottom: 40px; padding-top: 80px; text-align: center;">{{legend}}</legend>
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            <div class="input-group mb-3">
                {{ form.title(class='form-control input_user', placeholder='Judul postingan disini...') }}                
            </div>
            <div class="input-group mb-2">
                {{ form.content(class='form-control input_user', placeholder='Masukan isi postingan disini... ') }}                   
            </div> <br>
            <div class="d-flex justify-content-center mt-3 login_container">
                {{ form.submit(class='btn btn-primary mb-5') }}
            </div>                         
        </form>   
</div>
{{ ckeditor.load() }}
{{ ckeditor.config(name='content') }}

{% endblock content %}

app/templates/index.html
{% extends 'layout.html' %}


{% block index %}
<div class="container">
  <div class="row" style="margin-top: 100px;">


    <!-- Blog Entries Column -->
    <div class="col-md-8">
      <div class="text-center">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
      </div>

      <!-- Blog Post -->

      {% for post in posts.items %}
      <div class="card mb-4">
        <div class="card-body">
          <h2><a class="article-title" href="{{ url_for('posts.postingan', post_id=post.id) }}">{{ post.title }}</a></h2>
          <p class="card-text">{{post.content|safe|truncate(250)}}</p>
          <a href="{{url_for('posts.postingan',post_id=post.id)}}" class="btn btn-primary">Read More &rarr;</a>
        </div>
        <div class="card-footer text-muted">
          Posted on {{ post.date_posted.strftime('%d %B %Y') }} by
          <a href="{{ url_for('users.user_post', username=post.author.username) }}">{{post.author.username | capitalize}}</a>
        </div>
      </div>
      {% endfor %}

      {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
          {% if posts.page == page_num %}
            <a class="btn btn-primary mb-5" href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a>
          {% else %}
            <a class="btn btn-outline-primary mb-5" href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a>
          {% endif %}
        {% else %}
        ...
        {% endif %}
      {% endfor %}





      <!-- Pagination -->
      <!-- <nav style="margin-bottom: 50px;">
        <ul class="pagination ">
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">&laquo;</a>
          </li>
          <li class="page-item active" aria-current="page">
            <a class="page-link" href="#">1 <span class="sr-only">(current)</span></a>
          </li>
          <li class="page-item"><a class="page-link" href="#">2</a></li>
          <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item">
            <a class="page-link" href="#">&raquo;</a>
          </li>
        </ul>
      </nav> -->

    </div>
    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">

      <!-- Search Widget -->
      <div class="card">
        <h5 class="card-header">Search</h5>
        <div class="card-body">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-append">
              <button class="btn btn-secondary" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>

      <!-- Categories Widget -->
      <div class="card my-4">
        <h5 class="card-header">Categories</h5>
        <div class="card-body">
          <div class="row">
            <div class="col-lg-6">
              <ul class="list-unstyled mb-0">
                <li>
                  <a href="#">Web Design</a>
                </li>
                <li>
                  <a href="#">HTML</a>
                </li>
                <li>
                  <a href="#">Freebies</a>
                </li>
              </ul>
            </div>
            <div class="col-lg-6">
              <ul class="list-unstyled mb-0">
                <li>
                  <a href="#">JavaScript</a>
                </li>
                <li>
                  <a href="#">CSS</a>
                </li>
                <li>
                  <a href="#">Tutorials</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <!-- Side Widget -->
      <div class="card my-4">
        <h5 class="card-header">Side Widget</h5>
        <div class="card-body">
          You can put anything you want inside of these side widgets. They are easy to use, and feature the new
          Bootstrap 4 card containers!
        </div>
      </div>

    </div>

  </div>
  <!-- /.row -->
</div>

{% endblock index %}

app/templates/index.jinja2
{% extends 'layout.jinja2' %}


{% block index %}
<div class="container">
    <div class="row" style="margin-top: 100px;">

        <!-- Blog Entries Column -->
        <div class="col-md-8" >

            <h1>Python Flask
                <small>This my Blog</small>
            </h1>

            <!-- Blog Post -->
            <div class="card mb-4">
                <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
                <div class="card-body">
                    <h2 class="card-title">Post Title</h2>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid
                        atque, nulla? Quos cum ex quis soluta, a laboriosam. Dicta expedita corporis animi vero
                        voluptate voluptatibus possimus, veniam magni quis!</p>
                    <a href="#" class="btn btn-primary">Read More &rarr;</a>
                </div>
                <div class="card-footer text-muted">
                    Posted on January 1, 2020 by
                    <a href="#">Start Bootstrap</a>
                </div>
            </div>           
            <!-- Blog Post -->
            <div class="card mb-4">
              <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
              <div class="card-body">
                  <h2 class="card-title">Post Title</h2>
                  <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid
                      atque, nulla? Quos cum ex quis soluta, a laboriosam. Dicta expedita corporis animi vero
                      voluptate voluptatibus possimus, veniam magni quis!</p>
                  <a href="#" class="btn btn-primary">Read More &rarr;</a>
              </div>
              <div class="card-footer text-muted">
                  Posted on January 1, 2020 by
                  <a href="#">Start Bootstrap</a>
              </div>
          </div>                                      
            <nav style="margin-bottom: 50px;">
                <ul class="pagination ">
                  <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1" aria-disabled="true">&laquo;</a>
                  </li>
                  <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">1 <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="page-item"><a class="page-link" href="#">2</a></li>
                  <li class="page-item"><a class="page-link" href="#">3</a></li>
                  <li class="page-item">
                    <a class="page-link" href="#">&raquo;</a>
                  </li>
                </ul>
              </nav>        
        </div>
        <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-append">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">Web Design</a>
                  </li>
                  <li>
                    <a href="#">HTML</a>
                  </li>
                  <li>
                    <a href="#">Freebies</a>
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">JavaScript</a>
                  </li>
                  <li>
                    <a href="#">CSS</a>
                  </li>
                  <li>
                    <a href="#">Tutorials</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Side Widget</h5>
          <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
          </div>
        </div>

      </div>

    </div>
    <!-- /.row -->
</div>

{% endblock index %}

app/templates/postingan.html
{% extends 'layout.html' %}

{% block content %}
<!-- Page Content -->
<div class="container">

    <div class="row" style="margin-top: 100px;">

        <!-- Post Content Column -->
        <div class="col-lg-8">
            <a href="{{url_for('main.index')}}">
                <i class="fa fa-arrow-left" aria-hidden="true"></i> Kembali
            </a>
            {% if post.author == current_user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-4 mb-1"
                    href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                <button type="button" class="btn btn-danger btn-sm m-1 mt-4" data-toggle="modal"
                    data-target="#deleteModal">Delete</button>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
                aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel">Delete Postingan ?</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                            <form action="{{ url_for('posts.delete_post', post_id=post.id ) }}" method="post">
                                <input class="btn btn-danger" type="submit" value="Delete">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            <!-- Title -->
            <h1 class="mt-4">{{post.title}}</h1>

            <!-- Author -->
            <p class="lead">
                by
                <a href="{{ url_for('users.user_post', username=post.author.username) }}">{{post.author.username | capitalize}}</a>
            </p>

            <hr>

            <!-- Date/Time -->
            <p>Posted on {{post.date_posted.strftime('%d %B %Y')}}</p>

            <hr>

            <!-- Preview Image -->
            <!-- <img class="img-fluid rounded" src="http://placehold.it/900x300" alt=""> -->

            <hr>

            <!-- Post Content -->
            <p>{{ post.content|safe }}</p>
            <hr>

            <!-- Comments Form -->
            <div class="card my-4">
                <h5 class="card-header">Leave a Comment:</h5>
                <div class="card-body">
                    <form>
                        <div class="form-group">
                            <textarea class="form-control" rows="3"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>

            <!-- Single Comment -->
            <div class="media mb-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                    <h5 class="mt-0">Nama Komentar</h5>
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras
                    purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi
                    vulputate fringilla. Donec lacinia congue felis in faucibus.
                </div>
            </div>

            <!-- Comment with nested comments -->
            <!-- <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

          </div>
        </div> -->
            {% endblock content %}

app/templates/user_post.html
{% extends 'layout.html' %}


{% block index %}
<div class="container">
  <div class="row" style="margin-top: 100px;">


    <!-- Blog Entries Column -->
    <div class="col-md-8">
      <a href="{{url_for('main.index')}}">
        <i class="fa fa-arrow-left" aria-hidden="true"></i> Kembali
    </a> <br><br>
     <h2 class="mb-3">Posts by {{user.username}} ({{ posts.total }})</h2>
      <!-- Blog Post -->
      {% for post in posts.items %}
      <div class="card mb-4">
        <div class="card-body">
          <h2><a class="article-title" href="{{ url_for('posts.postingan', post_id=post.id) }}">{{ post.title }}</a></h2>
          <p class="card-text">{{post.content|safe|truncate(250)}}</p>
          <a href="{{url_for('posts.postingan',post_id=post.id)}}" class="btn btn-primary">Read More &rarr;</a>
        </div>
        <div class="card-footer text-muted">
          Posted on {{ post.date_posted.strftime('%d %B %Y') }} by
          <a href="{{ url_for('users.user_post', username=post.author.username) }}">{{post.author.username | capitalize}}</a>
        </div>
      </div>
      {% endfor %}

      {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
          {% if posts.page == page_num %}
            <a class="btn btn-primary mb-5" href="{{ url_for('users.user_post', username=user.username, page=page_num) }}">{{ page_num }}</a>
          {% else %}
            <a class="btn btn-outline-primary mb-5" href="{{ url_for('users.user_post',username=user.username, page=page_num) }}">{{ page_num }}</a>
          {% endif %}
        {% else %}
        ...
        {% endif %}
      {% endfor %}





      <!-- Pagination -->
      <!-- <nav style="margin-bottom: 50px;">
        <ul class="pagination ">
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">&laquo;</a>
          </li>
          <li class="page-item active" aria-current="page">
            <a class="page-link" href="#">1 <span class="sr-only">(current)</span></a>
          </li>
          <li class="page-item"><a class="page-link" href="#">2</a></li>
          <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item">
            <a class="page-link" href="#">&raquo;</a>
          </li>
        </ul>
      </nav> -->

    </div>
    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">

      <!-- Search Widget -->
      <div class="card">
        <h5 class="card-header">Search</h5>
        <div class="card-body">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-append">
              <button class="btn btn-secondary" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>

      <!-- Categories Widget -->
      <div class="card my-4">
        <h5 class="card-header">Categories</h5>
        <div class="card-body">
          <div class="row">
            <div class="col-lg-6">
              <ul class="list-unstyled mb-0">
                <li>
                  <a href="#">Web Design</a>
                </li>
                <li>
                  <a href="#">HTML</a>
                </li>
                <li>
                  <a href="#">Freebies</a>
                </li>
              </ul>
            </div>
            <div class="col-lg-6">
              <ul class="list-unstyled mb-0">
                <li>
                  <a href="#">JavaScript</a>
                </li>
                <li>
                  <a href="#">CSS</a>
                </li>
                <li>
                  <a href="#">Tutorials</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <!-- Side Widget -->
      <div class="card my-4">
        <h5 class="card-header">Side Widget</h5>
        <div class="card-body">
          You can put anything you want inside of these side widgets. They are easy to use, and feature the new
          Bootstrap 4 card containers!
        </div>
      </div>

    </div>

  </div>
  <!-- /.row -->
</div>

{% endblock index %}